# Site settings
title: "Echelon Initiative"
email: node@echelon.net
description: "We are building safer tomorrows"
title_description: "We are building safer tomorrows"
title_image: "/web-app-manifest-192x192.png"
post_limit: 5

# Social usernames/URLs


# Footer
footer_left: ""
footer_right: "&lt;/&gt;  <a href=\"https://rebelief.github.io\">Refresh Page</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
