# Site settings
title: "Echelon Initiative"
email: node@echelon.net
description: "We are building safer tomorrows"
title_description: "We are building safer tomorrows"
title_image: "<blockquote class="imgur-embed-pub" lang="en" data-id="a/TfUj0CZ" data-context="false" ><a href="//imgur.com/a/TfUj0CZ"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>"
post_limit: 5

# Social usernames/URLs


# Footer
footer_left: ""
footer_right: "&lt;/&gt;  <a href=\"https://rebelief.github.io\">Refresh Page</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
