# Site settings
title: "Echelon Initiative"
email: node@echelon.net
description: "We are building safer tomorrows"
baseurl: ""
url: ""
title_description: "We are building safer tomorrows"
title_image: "https://github.com/Rebelief/rebelief.github.io/blob/be65f843d168645eb0808e90a24086b56b84e8d3/favicons/web-app-manifest-512x512.png"
google_analytics: ""
disqus_account: 
github_repository:
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username: 

# Footer
footer_left: ""
footer_right: "&lt;/&gt; on <a href=\"https://rebelief.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
